### ISSUE TITLE
p-value limit

### ISSUE THREAD

**Issue by liezeltamon** [bernatgel/regioneR#6]
Hi,

Just wanted to ask whether there's a built-in limit such that the p-value can't go lower than 0.0001. This is the lowest value I've been getting and I just want to make sure that it is safe to state that the p-value could be <= 0.0001 (based on the figure the value is probably lower). I've looked at the permTest code and I don't see that you are rounding off or setting an explicit limit. Would be helpful if you could clarify please, thank you!

<img width="648" alt="Screenshot 2021-11-02 at 18 33 13" src="https://user-images.githubusercontent.com/45236685/139830727-c2de6213-f256-4874-a649-4c93106c3328.png">

**Comment by bernatgel** [comment]
Hi @liezeltamon 

regioneR computes an empirical p-value based on the permutations, so the actual minimal possible p-value is 1/num_permutations. In your case, 1/10000=0.0001. If you increase the nuumber of permutations you'll decrease your minimal p-value.

With your analysis, it seems the difference is so extreme that you can get almost any p-value you want. What we do in general is say p-val < 0.0001 instead of an equality, 

Does it make sense?

**Comment by liezeltamon** [comment]
Got it, thanks so much!
